# 配置tomcat
server:
  port: 8088
  servlet:
   context-path: /springboot

# JDBC
spring:
  datasource:
    name: my_datasource
    # 数据源类型：Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # 配置Druid的其他参数，以下配置必须增加一个配置文件才能有效 DruidConfig.java
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html

# 设置mybatis,该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.jc.model  # 注意：对应实体类的路径
  # 设置驼峰命名
  configuration:
    mapUnderscoreToCamelCase: true

# 打印sql
#logging:
#  level:
#    com.jc.dao.sec.user: DEBUG